# Copyright LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
name: excute tests 
 
on:
  workflow_call:
jobs:         
    call-test-workflow-windows-qeax:
        # needs: prepare-test
        uses: ./.github/workflows/TestModelCheck.yml
        with:
            runs-on: windows-latest
            model-path: ./Model.qeax
        secrets: inherit
    
    call-test-workflow-windows-eapx:
        # needs: prepare-test
        uses: ./.github/workflows/TestModelCheck.yml
        with:
            runs-on: windows-latest
            model-path: ./PWC.eapx
        secrets: inherit

    call-test-workflow-windows-filenotfound:
        # needs: prepare-test
        uses: ./.github/workflows/TestModelCheck.yml
        with:
            runs-on: windows-latest
            model-path: ./filenotfound.qeax
            expected-exitcode: -2
        secrets: inherit

    call-test-workflow-linux:
        # needs: prepare-test
        uses: ./.github/workflows/TestModelCheck.yml
        with:
            runs-on: ubuntu-latest
            model-path: ./Model.qeax
        secrets: inherit

    call-test-remove-windows-qeax:
        # needs: prepare-test
        uses: ./.github/workflows/TestRemovePrerenderedDiagrams.yml
        with:
            runs-on: windows-latest
            model-path: ./Model.qeax
        secrets: inherit
    
    call-test-remove-windows-eapx:
        # needs: prepare-test
        uses: ./.github/workflows/TestRemovePrerenderedDiagrams.yml
        with:
            runs-on: windows-latest
            model-path: ./PWC.eapx
        secrets: inherit

    call-test-workflow-remove-filenotfound:
        # needs: prepare-test
        uses: ./.github/workflows/TestRemovePrerenderedDiagrams.yml
        with:
            runs-on: windows-latest
            model-path: ./filenotfound.qeax
            expected-exitcode: -2
        secrets: inherit    