# Copyright LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
name: Push on feature 

on:
    push:
      branches-ignore:
        - main          
jobs:
    call-build-workflow:
        uses: ./.github/workflows/Build.yml
        with:
            version: ${{vars.PRODUCTVERSION}}
            runs-on: windows-latest
        secrets: inherit
    
    call-executetests-workflow:
        needs: call-build-workflow
        uses: ./.github/workflows/executetests.yml
        secrets: inherit
    