# Copyright LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.name: publish single artifact
 
on:
  workflow_call:
    inputs:
      nexus-path:
        required: true
        type: string
jobs:

    call-publishartifact-workflow-1:
      uses: ./.github/workflows/publishartifact.yml
      with:
        nexus-path: ${{inputs.nexus-path}}
        artifact-name: LemonTree.Pipeline.Tools.ModelCheck.Linux
        binary-name: LemonTree.Pipeline.Tools.ModelCheck
      secrets: inherit

    call-publishartifact-workflow-2:
      uses: ./.github/workflows/publishartifact.yml
      with:
        nexus-path: ${{inputs.nexus-path}}
        artifact-name: LemonTree.Pipeline.Tools.ModelCheck.Windows
        binary-name: LemonTree.Pipeline.Tools.ModelCheck.exe
      secrets: inherit   

    call-publishartifact-workflow-3:
      uses: ./.github/workflows/publishartifact.yml
      with:
        nexus-path: ${{inputs.nexus-path}}
        artifact-name: LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.Windows
        binary-name: LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exe
      secrets: inherit          

    call-publishartifact-workflow-4:
      uses: ./.github/workflows/publishartifact.yml
      with:
        nexus-path: ${{inputs.nexus-path}}
        artifact-name: LemonTree.Pipeline.Tools.SetFilterInSessionFile.Windows
        binary-name: LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe
      secrets: inherit        

           